ComRV: Avoid compiler error when casting function pointers
When compiling with GCC 9.3.1 I was seeing a compiler error as we cast
a pointer to this function:

  extern int _bfd_int_bfd_0
    (bfd *) ATTRIBUTE_HIDDEN;

like this:

  #define _bfd_nolink_bfd_get_section_user_sort_data \
    ((int (*) (asection *, struct bfd_link_info *)) _bfd_int_bfd_0)

The compiler complains:

  binutils-gdb/bfd/libbfd.h:549:4: error: cast between incompatible function types from ‘int (*)(bfd *)’ {aka ‘int(*)(struct bfd *)’} to ‘int (*)(asection *, struct bfd_link_info *)’ {aka ‘int (*)(struct bfd_section *, struct bfd_link_info *)’} [-Werror=cast-function-type]
    549 |   ((int (*) (asection *, struct bfd_link_info *)) _bfd_int_bfd_0)
        |    ^
  ./bfd.h:7607:3: note: in expansion of macro ‘_bfd_nolink_bfd_get_section_user_sort_data’
   7607 |   NAME##_bfd_get_section_user_sort_data
        |   ^~~~
  ../../binutils-gdb/bfd/verilog.c:428:3: note: in expansion of macro ‘BFD_JUMP_TABLE_LINK’
    428 |   BFD_JUMP_TABLE_LINK (_bfd_nolink),
        |   ^~~~~~~~~~~~~~~~~~~

GCC was unhappy with the number of arguments changing.  Fixed by
adding a new two argument function with the correct signature and
using that instead of _bfd_int_bfd_0.